language: ruby
rvm:
- 2.4.5
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec
deploy:
  api_key:
    secure: 4Q+L/rIa3uB6d/IxsMKsY41ytn9jz+IcrX1viuSmkwsQd8ap5lxxljbRPiafyegSaR2zpna1yI0LVffUtH2FRx7EGb3pA6k6v9962vkE+bDbq+s+mpG6SygwlXe6wLSHVN2+yufQdQ18q4QGsqQN9ox0DVLtid2kmwbKtxofHSkmrJsgnf18761rPAddgHxlkHMj4ff8ZeMzz0JJIw3MQaIgbJJXC/pg1yd3rTJJ5JB+OR/ey0ZDoSsep4MRnXYuuf93Q5gSdvWGqIeSocK3rrC6cVCw0YI7KJcHqafrFsNZTpUF0yYky2ujraq2El7QmjHaKSibcZTlixbh2Gx7dvziEv4J9ySsa4u+Ozu1LVcPUs3OqbRPRH7wDY07OvZHi5dWm74klO+yRRcfagf9CNiuHyMc9ken4/vpgBDxGUkhM9DZg/Zkusk7jMCWvSgo8RWX4K2l7GbpW2ih1X12b2pazeGd1mOGVQXo6v4xGAUy4XIORgoGC3AlOCqiDjUzsdjNCEzNkPZQs5nRkE0MsqPnj0cJbesFtQephyoItOBGVpeX0BWx01kPfF/Ihi++fVVkGJ7iF81/1m11mUGc0yGUUTPl2IGi2f3f1EWKCniU/cw2PUj4qprRFpc1oiKIU7lyTGM/GGafx8qVgtM+9OgtRJZvAgc45cGnxV1iwto=
  app: calm-tundra-59037
  
